# Generated by Django 4.1.5 on 2024-08-14 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=30)),
                ('since_year', models.IntegerField()),
                ('slogan', models.CharField(max_length=60)),
                ('vision', models.TextField(max_length=400)),
            ],
        ),
    ]
